# Generated by Django 2.2.3 on 2019-07-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190705_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='player',
            name='season_points',
        ),
    ]
