# Generated by Django 2.2.3 on 2019-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20190708_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hometown',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
