# Generated by Django 2.2.3 on 2019-07-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pic_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='wins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
